import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
//  import 'react-toastify/dist/ReactToastify.css';
//  import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* for add font */}
      
      <body className={inter.className}>
      {/* <ToastContainer /> */}

<Nav/>
       {children}
<Footer/>    
    </body>
    </html>
  );
}
